import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/Navigation/Footer";
import Image from "next/image";
import MainNav from "@/Navigation/ManiNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <div className="fixed inset-0 -z-10">
          <Image
            src="/random.jpg"
            alt="Background"
            fill
            className="object-cover object-center"
            priority
          />
        </div>
         <MainNav />
       
        <main>{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
